### ISSUE TITLE
Problem with requirement.txt package version handling

### ISSUE THREAD

**Issue by psychemedia** [jupyter/repo2docker#708]
### Bug description
Trying to install the following via `requirements.txt`:

```
pygdal=="`gdal-config --version`.*"
```

as per [`pygdal` docs](https://pypi.org/project/pygdal/).

#### Expected behaviour
The package should build. (The `pip install` works fine from the command line.)

#### Actual behaviour

I get a quote mismatch error in the build step.

```
ERROR: Exception:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_internal/cli/base_command.py",line 178, in main
    status = self.run(options, args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_internal/commands/install.py",line 326, in run
    self.name, wheel_cache
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_internal/cli/base_command.py",line 288, in populate_requirement_set
    use_pep517=options.use_pep517):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 112, in parse_requirements
    for req in req_iter:
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 173, in process_line
    shlex.split(options_str), defaults)  # type: ignore
  File "/srv/conda/envs/notebook/lib/python3.7/shlex.py", line 305, in split
    return list(lex)
  File "/srv/conda/envs/notebook/lib/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/srv/conda/envs/notebook/lib/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/srv/conda/envs/notebook/lib/python3.7/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

### How to reproduce

Try launching https://github.com/ouseful-testing/pygdal on MyBinder.

**Comment by betatim** [comment]
I don't think you can put things in a `requirements.txt` that need evaluating by the shell. It can only contain strings. So you will have to write the version explicitly.

The instructions on the pygdal page assume that you shell will run the command in between the ` quotes and replace it with the output of the command.

**Comment by psychemedia** [comment]
Ah, ok... so I guess that sort of package install (where the package to be installed needs to be set to a version dependent on the version of another package which is not in itself pinned) will have to be provided via a `postBuild` step?

**Comment by betatim** [comment]
Jupp.
